# Pods for YOURAPP
pod 'Firebase/Messaging'
pod 'GoogleToolboxForMac'
pod 'PushNotifications'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eat_for_me' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eat_for_me

  target 'eat_for_me-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'eat_for_meTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
